"""Build public reference SQL from versioned CSVs; never export student records."""
import csv
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'app'))
from seed_db import PROFICIENCY_LEVELS, INDUSTRIES, DEPARTMENTS

def quote(value):
    if value is None or value == '': return 'null'
    return "'" + str(value).replace("'", "''") + "'"

def rows(name):
    with (ROOT / 'data' / (name + '.csv')).open(encoding='utf-8', newline='') as f:
        return list(csv.DictReader(f))

def lookup(table, column, value):
    return f'(select id from {table} where {column}={quote(value)})'

def build():
    out = ['-- Generated by scripts/build_cloud_seed.py. Public reference data only.']
    def insert(table, columns, values):
        out.append(f'insert into {table} ({columns}) values ({",".join(values)}) on conflict do nothing;')
    for row in PROFICIENCY_LEVELS:
        insert('proficiency_levels', 'rank,code,label,description', [quote(v) for v in row])
    for name in INDUSTRIES: insert('industries','name',[quote(name)])
    for name, faculty in DEPARTMENTS: insert('departments','name,faculty',[quote(name),quote(faculty)])
    for cat in sorted({r['category'] for r in rows('skill_taxonomy')}):
        insert('skill_categories','name',[quote(cat)])
    for r in rows('skill_taxonomy'):
        insert('skills','name,slug,category_id',[quote(r['skill']),quote(r['slug']),lookup('skill_categories','name',r['category'])])
    for r in rows('careers'):
        insert('careers','name,slug,description',[quote(r[k]) for k in ['name','slug','description']])
    for r in rows('career_skills'):
        insert('career_required_skills','career_id,skill_id,target_rank,weight',[lookup('careers','slug',r['career_slug']),lookup('skills','slug',r['skill_slug']),quote(r['target_rank']),quote(r['weight'])])
    for r in rows('skill_aliases'):
        insert('skill_aliases','skill_id,alias',[lookup('skills','slug',r['skill_slug']),quote(r['alias'])])
    for r in rows('opportunities'):
        cols=['slug','title','category','organization','description','url','is_remote','min_level','max_level','deadline','source']
        r['is_remote']='true' if r['is_remote']=='1' else 'false'
        r['source']='sample' # CSV listings have example.org URLs, not verified openings.
        insert('opportunities',','.join(cols),[quote(r[k]) for k in cols])
    for r in rows('opportunity_skills'):
        insert('opportunity_skills','opportunity_id,skill_id,weight',[lookup('opportunities','slug',r['opp_slug']),lookup('skills','slug',r['skill_slug']),quote(r['weight'])])
    for r in rows('opportunity_careers'):
        insert('opportunity_careers','opportunity_id,career_id',[lookup('opportunities','slug',r['opp_slug']),lookup('careers','slug',r['career_slug'])])
    return '\n'.join(out)+'\n'

if __name__=='__main__':
    (ROOT/'db'/'cloud_seed.sql').write_text(build(),encoding='utf-8')
    print('Generated db/cloud_seed.sql (reference data only).')
